name: food_delivery_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  intro_slider: ^4.2.1
  lottie: ^3.1.2
  onboarding: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:    
    - assets/images/
    - assets/animations/
